name: Run Script at 9:16 AM IST

on: [push]

# on:
#   schedule:
#     - cron: '46 3 * * *'  # 3:46 AM UTC = 9:16 AM IST

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: npm start
